// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tunnel.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Dolittle.Runtime.Events.Relativity {
  public static partial class Tunnel
  {
    static readonly string __ServiceName = "relativity.Tunnel";

    static readonly grpc::Marshaller<global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage> __Marshaller_ParticleSubscriptionsMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.Runtime.Events.Relativity.ParticleMessage> __Marshaller_ParticleMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Runtime.Events.Relativity.ParticleMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage, global::Dolittle.Runtime.Events.Relativity.ParticleMessage> __Method_Open = new grpc::Method<global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage, global::Dolittle.Runtime.Events.Relativity.ParticleMessage>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Open",
        __Marshaller_ParticleSubscriptionsMessage,
        __Marshaller_ParticleMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.Runtime.Events.Relativity.TunnelReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Tunnel</summary>
    public abstract partial class TunnelBase
    {
      public virtual global::System.Threading.Tasks.Task Open(global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage request, grpc::IServerStreamWriter<global::Dolittle.Runtime.Events.Relativity.ParticleMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Tunnel</summary>
    public partial class TunnelClient : grpc::ClientBase<TunnelClient>
    {
      /// <summary>Creates a new client for Tunnel</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TunnelClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Tunnel that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TunnelClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TunnelClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TunnelClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.Runtime.Events.Relativity.ParticleMessage> Open(global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Open(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.Runtime.Events.Relativity.ParticleMessage> Open(global::Dolittle.Runtime.Events.Relativity.ParticleSubscriptionsMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Open, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TunnelClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TunnelClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TunnelBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Open, serviceImpl.Open).Build();
    }

  }
}
#endregion
