// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/quantum_tunnel.proto
// Original file comments:
// ---------------------------------------------------------------------------------------------
//  Copyright (c) Dolittle. All rights reserved.
//  Licensed under the MIT License. See LICENSE in the project root for license information.
// --------------------------------------------------------------------------------------------
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Dolittle.Runtime.Grpc.Interaction.Grpc {
  /// <summary>
  /// Represents the service for working with quantum tunnel
  /// </summary>
  public static partial class QuantumTunnelService
  {
    static readonly string __ServiceName = "dolittle.events.relativity.QuantumTunnelService";

    static readonly grpc::Marshaller<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel> __Marshaller_OpenTunnel = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext> __Marshaller_CommittedEventStreamWithContext = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext.Parser.ParseFrom);

    static readonly grpc::Method<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel, global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext> __Method_Open = new grpc::Method<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel, global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Open",
        __Marshaller_OpenTunnel,
        __Marshaller_CommittedEventStreamWithContext);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dolittle.Runtime.Grpc.Interaction.Grpc.QuantumTunnelReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QuantumTunnelService</summary>
    public abstract partial class QuantumTunnelServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Open(global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel request, grpc::IServerStreamWriter<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QuantumTunnelService</summary>
    public partial class QuantumTunnelServiceClient : grpc::ClientBase<QuantumTunnelServiceClient>
    {
      /// <summary>Creates a new client for QuantumTunnelService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public QuantumTunnelServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QuantumTunnelService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public QuantumTunnelServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected QuantumTunnelServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected QuantumTunnelServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext> Open(global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Open(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContext> Open(global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnel request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Open, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override QuantumTunnelServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QuantumTunnelServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(QuantumTunnelServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Open, serviceImpl.Open).Build();
    }

  }
}
#endregion
