// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/committed_event_stream_with_context.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Grpc.Interaction {

  /// <summary>Holder for reflection information generated from dolittle/interaction/events.relativity/committed_event_stream_with_context.proto</summary>
  public static partial class CommittedEventStreamWithContextReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/interaction/events.relativity/committed_event_stream_with_context.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommittedEventStreamWithContextReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClBkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVsYXRpdml0eS9jb21t",
            "aXR0ZWRfZXZlbnRfc3RyZWFtX3dpdGhfY29udGV4dC5wcm90bxIaZG9saXR0",
            "bGUuZXZlbnRzLnJlbGF0aXZpdHkaQ2RvbGl0dGxlL2ludGVyYWN0aW9uL2V2",
            "ZW50cy5yZWxhdGl2aXR5L2NvbW1pdHRlZF9ldmVudF9zdHJlYW0ucHJvdG8a",
            "PmRvbGl0dGxlL2ludGVyYWN0aW9uL2V2ZW50cy5yZWxhdGl2aXR5L2V4ZWN1",
            "dGlvbl9jb250ZXh0LnByb3RvIqIBCh9Db21taXR0ZWRFdmVudFN0cmVhbVdp",
            "dGhDb250ZXh0EkAKBmNvbW1pdBgBIAEoCzIwLmRvbGl0dGxlLmV2ZW50cy5y",
            "ZWxhdGl2aXR5LkNvbW1pdHRlZEV2ZW50U3RyZWFtEj0KB2NvbnRleHQYAiAB",
            "KAsyLC5kb2xpdHRsZS5ldmVudHMucmVsYXRpdml0eS5FeGVjdXRpb25Db250",
            "ZXh0QiSqAiFEb2xpdHRsZS5SdW50aW1lLkdycGMuSW50ZXJhY3Rpb25iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStreamReflection.Descriptor, global::Dolittle.Runtime.Grpc.Interaction.ExecutionContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStreamWithContext), global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStreamWithContext.Parser, new[]{ "Commit", "Context" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents a committed event stream with the Execution Context
  /// </summary>
  public sealed partial class CommittedEventStreamWithContext : pb::IMessage<CommittedEventStreamWithContext> {
    private static readonly pb::MessageParser<CommittedEventStreamWithContext> _parser = new pb::MessageParser<CommittedEventStreamWithContext>(() => new CommittedEventStreamWithContext());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommittedEventStreamWithContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStreamWithContextReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext(CommittedEventStreamWithContext other) : this() {
      Commit = other.commit_ != null ? other.Commit.Clone() : null;
      Context = other.context_ != null ? other.Context.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext Clone() {
      return new CommittedEventStreamWithContext(this);
    }

    /// <summary>Field number for the "commit" field.</summary>
    public const int CommitFieldNumber = 1;
    private global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStream commit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStream Commit {
      get { return commit_; }
      set {
        commit_ = value;
      }
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 2;
    private global::Dolittle.Runtime.Grpc.Interaction.ExecutionContext context_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Grpc.Interaction.ExecutionContext Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommittedEventStreamWithContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommittedEventStreamWithContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Commit, other.Commit)) return false;
      if (!object.Equals(Context, other.Context)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (commit_ != null) hash ^= Commit.GetHashCode();
      if (context_ != null) hash ^= Context.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (commit_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Commit);
      }
      if (context_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Context);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (commit_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Commit);
      }
      if (context_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Context);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommittedEventStreamWithContext other) {
      if (other == null) {
        return;
      }
      if (other.commit_ != null) {
        if (commit_ == null) {
          commit_ = new global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStream();
        }
        Commit.MergeFrom(other.Commit);
      }
      if (other.context_ != null) {
        if (context_ == null) {
          context_ = new global::Dolittle.Runtime.Grpc.Interaction.ExecutionContext();
        }
        Context.MergeFrom(other.Context);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (commit_ == null) {
              commit_ = new global::Dolittle.Runtime.Grpc.Interaction.CommittedEventStream();
            }
            input.ReadMessage(commit_);
            break;
          }
          case 18: {
            if (context_ == null) {
              context_ = new global::Dolittle.Runtime.Grpc.Interaction.ExecutionContext();
            }
            input.ReadMessage(context_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
