// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/quantum_tunnel.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Grpc.Interaction.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/interaction/events.relativity/quantum_tunnel.proto</summary>
  public static partial class QuantumTunnelReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/interaction/events.relativity/quantum_tunnel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuantumTunnelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVsYXRpdml0eS9xdWFu",
            "dHVtX3R1bm5lbC5wcm90bxIaZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHka",
            "OGRvbGl0dGxlL2ludGVyYWN0aW9uL2V2ZW50cy5yZWxhdGl2aXR5L29wZW5f",
            "dHVubmVsLnByb3RvGlBkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVs",
            "YXRpdml0eS9jb21taXR0ZWRfZXZlbnRfc3RyZWFtX3dpdGhfY29udGV4dC5w",
            "cm90bzKHAQoUUXVhbnR1bVR1bm5lbFNlcnZpY2USbwoET3BlbhImLmRvbGl0",
            "dGxlLmV2ZW50cy5yZWxhdGl2aXR5Lk9wZW5UdW5uZWwaOy5kb2xpdHRsZS5l",
            "dmVudHMucmVsYXRpdml0eS5Db21taXR0ZWRFdmVudFN0cmVhbVdpdGhDb250",
            "ZXh0IgAwAUItqgIqRG9saXR0bGUuUnVudGltZS5HcnBjLkludGVyYWN0aW9u",
            "LlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Grpc.Interaction.Protobuf.OpenTunnelReflection.Descriptor, global::Dolittle.Runtime.Grpc.Interaction.Protobuf.CommittedEventStreamWithContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
