// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/versioned_event_source.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Grpc.Interaction.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/interaction/events.relativity/versioned_event_source.proto</summary>
  public static partial class VersionedEventSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/interaction/events.relativity/versioned_event_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VersionedEventSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkNkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVsYXRpdml0eS92ZXJz",
            "aW9uZWRfZXZlbnRfc291cmNlLnByb3RvEhpkb2xpdHRsZS5ldmVudHMucmVs",
            "YXRpdml0eRoRc3lzdGVtL2d1aWQucHJvdG8aQWRvbGl0dGxlL2ludGVyYWN0",
            "aW9uL2V2ZW50cy5yZWxhdGl2aXR5L2V2ZW50X3NvdXJjZV92ZXJzaW9uLnBy",
            "b3RvIp4BChRWZXJzaW9uZWRFdmVudFNvdXJjZRI/Cgd2ZXJzaW9uGAEgASgL",
            "Mi4uZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHkuRXZlbnRTb3VyY2VWZXJz",
            "aW9uEiMKC2V2ZW50U291cmNlGAIgASgLMg4uZG9saXR0bGUuZ3VpZBIgCghh",
            "cnRpZmFjdBgDIAEoCzIOLmRvbGl0dGxlLmd1aWRCLaoCKkRvbGl0dGxlLlJ1",
            "bnRpbWUuR3JwYy5JbnRlcmFjdGlvbi5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::System.Protobuf.GuidReflection.Descriptor, global::Dolittle.Runtime.Grpc.Interaction.Protobuf.EventSourceVersionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Grpc.Interaction.Protobuf.VersionedEventSource), global::Dolittle.Runtime.Grpc.Interaction.Protobuf.VersionedEventSource.Parser, new[]{ "Version", "EventSource", "Artifact" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents a versioned event source
  /// </summary>
  public sealed partial class VersionedEventSource : pb::IMessage<VersionedEventSource> {
    private static readonly pb::MessageParser<VersionedEventSource> _parser = new pb::MessageParser<VersionedEventSource>(() => new VersionedEventSource());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VersionedEventSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Grpc.Interaction.Protobuf.VersionedEventSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource(VersionedEventSource other) : this() {
      Version = other.version_ != null ? other.Version.Clone() : null;
      EventSource = other.eventSource_ != null ? other.EventSource.Clone() : null;
      Artifact = other.artifact_ != null ? other.Artifact.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource Clone() {
      return new VersionedEventSource(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private global::Dolittle.Runtime.Grpc.Interaction.Protobuf.EventSourceVersion version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Grpc.Interaction.Protobuf.EventSourceVersion Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "eventSource" field.</summary>
    public const int EventSourceFieldNumber = 2;
    private global::System.Protobuf.guid eventSource_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid EventSource {
      get { return eventSource_; }
      set {
        eventSource_ = value;
      }
    }

    /// <summary>Field number for the "artifact" field.</summary>
    public const int ArtifactFieldNumber = 3;
    private global::System.Protobuf.guid artifact_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid Artifact {
      get { return artifact_; }
      set {
        artifact_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VersionedEventSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VersionedEventSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Version, other.Version)) return false;
      if (!object.Equals(EventSource, other.EventSource)) return false;
      if (!object.Equals(Artifact, other.Artifact)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (version_ != null) hash ^= Version.GetHashCode();
      if (eventSource_ != null) hash ^= EventSource.GetHashCode();
      if (artifact_ != null) hash ^= Artifact.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (version_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Version);
      }
      if (eventSource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EventSource);
      }
      if (artifact_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Artifact);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (version_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Version);
      }
      if (eventSource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EventSource);
      }
      if (artifact_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Artifact);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VersionedEventSource other) {
      if (other == null) {
        return;
      }
      if (other.version_ != null) {
        if (version_ == null) {
          version_ = new global::Dolittle.Runtime.Grpc.Interaction.Protobuf.EventSourceVersion();
        }
        Version.MergeFrom(other.Version);
      }
      if (other.eventSource_ != null) {
        if (eventSource_ == null) {
          eventSource_ = new global::System.Protobuf.guid();
        }
        EventSource.MergeFrom(other.EventSource);
      }
      if (other.artifact_ != null) {
        if (artifact_ == null) {
          artifact_ = new global::System.Protobuf.guid();
        }
        Artifact.MergeFrom(other.Artifact);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (version_ == null) {
              version_ = new global::Dolittle.Runtime.Grpc.Interaction.Protobuf.EventSourceVersion();
            }
            input.ReadMessage(version_);
            break;
          }
          case 18: {
            if (eventSource_ == null) {
              eventSource_ = new global::System.Protobuf.guid();
            }
            input.ReadMessage(eventSource_);
            break;
          }
          case 26: {
            if (artifact_ == null) {
              artifact_ = new global::System.Protobuf.guid();
            }
            input.ReadMessage(artifact_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
