// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/events.relativity/quantum_tunnel.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/events.relativity/quantum_tunnel.proto</summary>
  public static partial class QuantumTunnelReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/events.relativity/quantum_tunnel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuantumTunnelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9kb2xpdHRsZS9ldmVudHMucmVsYXRpdml0eS9xdWFudHVtX3R1bm5lbC5w",
            "cm90bxIaZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHkaLGRvbGl0dGxlL2V2",
            "ZW50cy5yZWxhdGl2aXR5L29wZW5fdHVubmVsLnByb3RvGjdkb2xpdHRsZS9l",
            "dmVudHMucmVsYXRpdml0eS9jb21taXR0ZWRfZXZlbnRfc3RyZWFtLnByb3Rv",
            "MnwKFFF1YW50dW1UdW5uZWxTZXJ2aWNlEmQKBE9wZW4SJi5kb2xpdHRsZS5l",
            "dmVudHMucmVsYXRpdml0eS5PcGVuVHVubmVsGjAuZG9saXR0bGUuZXZlbnRz",
            "LnJlbGF0aXZpdHkuQ29tbWl0dGVkRXZlbnRTdHJlYW0iADABQi6qAitEb2xp",
            "dHRsZS5SdW50aW1lLkV2ZW50cy5SZWxhdGl2aXR5LlByb3RvYnVmYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Events.Relativity.Protobuf.OpenTunnelReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Protobuf.CommittedEventStreamReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
