// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/committed_event_stream.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/interaction/events.relativity/committed_event_stream.proto</summary>
  public static partial class CommittedEventStreamReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/interaction/events.relativity/committed_event_stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommittedEventStreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkNkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVsYXRpdml0eS9jb21t",
            "aXR0ZWRfZXZlbnRfc3RyZWFtLnByb3RvEhpkb2xpdHRsZS5ldmVudHMucmVs",
            "YXRpdml0eRoRc3lzdGVtL2d1aWQucHJvdG8aQ2RvbGl0dGxlL2ludGVyYWN0",
            "aW9uL2V2ZW50cy5yZWxhdGl2aXR5L3ZlcnNpb25lZF9ldmVudF9zb3VyY2Uu",
            "cHJvdG8aO2RvbGl0dGxlL2ludGVyYWN0aW9uL2V2ZW50cy5yZWxhdGl2aXR5",
            "L2V2ZW50X2VudmVsb3BlLnByb3RvIvsBChRDb21taXR0ZWRFdmVudFN0cmVh",
            "bRJACgZzb3VyY2UYASABKAsyMC5kb2xpdHRsZS5ldmVudHMucmVsYXRpdml0",
            "eS5WZXJzaW9uZWRFdmVudFNvdXJjZRIQCghzZXF1ZW5jZRgCIAEoBBIaCgJp",
            "ZBgDIAEoCzIOLmRvbGl0dGxlLmd1aWQSEQoJdGltZVN0YW1wGAQgASgDEiUK",
            "DWNvcnJlbGF0aW9uSWQYBSABKAsyDi5kb2xpdHRsZS5ndWlkEjkKBmV2ZW50",
            "cxgGIAMoCzIpLmRvbGl0dGxlLmV2ZW50cy5yZWxhdGl2aXR5LkV2ZW50RW52",
            "ZWxvcGVCLqoCK0RvbGl0dGxlLlJ1bnRpbWUuRXZlbnRzLlJlbGF0aXZpdHku",
            "UHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::System.Protobuf.GuidReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Protobuf.VersionedEventSourceReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelopeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Events.Relativity.Protobuf.CommittedEventStream), global::Dolittle.Runtime.Events.Relativity.Protobuf.CommittedEventStream.Parser, new[]{ "Source", "Sequence", "Id", "TimeStamp", "CorrelationId", "Events" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents a committed event stream
  /// </summary>
  public sealed partial class CommittedEventStream : pb::IMessage<CommittedEventStream> {
    private static readonly pb::MessageParser<CommittedEventStream> _parser = new pb::MessageParser<CommittedEventStream>(() => new CommittedEventStream());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommittedEventStream> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Events.Relativity.Protobuf.CommittedEventStreamReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStream() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStream(CommittedEventStream other) : this() {
      Source = other.source_ != null ? other.Source.Clone() : null;
      sequence_ = other.sequence_;
      Id = other.id_ != null ? other.Id.Clone() : null;
      timeStamp_ = other.timeStamp_;
      CorrelationId = other.correlationId_ != null ? other.CorrelationId.Clone() : null;
      events_ = other.events_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStream Clone() {
      return new CommittedEventStream(this);
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 1;
    private global::Dolittle.Runtime.Events.Relativity.Protobuf.VersionedEventSource source_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Protobuf.VersionedEventSource Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "sequence" field.</summary>
    public const int SequenceFieldNumber = 2;
    private ulong sequence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Sequence {
      get { return sequence_; }
      set {
        sequence_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private global::System.Protobuf.guid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "timeStamp" field.</summary>
    public const int TimeStampFieldNumber = 4;
    private long timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 5;
    private global::System.Protobuf.guid correlationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = value;
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope> _repeated_events_codec
        = pb::FieldCodec.ForMessage(50, global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope> events_ = new pbc::RepeatedField<global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommittedEventStream);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommittedEventStream other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Source, other.Source)) return false;
      if (Sequence != other.Sequence) return false;
      if (!object.Equals(Id, other.Id)) return false;
      if (TimeStamp != other.TimeStamp) return false;
      if (!object.Equals(CorrelationId, other.CorrelationId)) return false;
      if(!events_.Equals(other.events_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (source_ != null) hash ^= Source.GetHashCode();
      if (Sequence != 0UL) hash ^= Sequence.GetHashCode();
      if (id_ != null) hash ^= Id.GetHashCode();
      if (TimeStamp != 0L) hash ^= TimeStamp.GetHashCode();
      if (correlationId_ != null) hash ^= CorrelationId.GetHashCode();
      hash ^= events_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (source_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Source);
      }
      if (Sequence != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sequence);
      }
      if (id_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Id);
      }
      if (TimeStamp != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimeStamp);
      }
      if (correlationId_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(CorrelationId);
      }
      events_.WriteTo(output, _repeated_events_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (source_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Source);
      }
      if (Sequence != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sequence);
      }
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (TimeStamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeStamp);
      }
      if (correlationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CorrelationId);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommittedEventStream other) {
      if (other == null) {
        return;
      }
      if (other.source_ != null) {
        if (source_ == null) {
          source_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.VersionedEventSource();
        }
        Source.MergeFrom(other.Source);
      }
      if (other.Sequence != 0UL) {
        Sequence = other.Sequence;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          id_ = new global::System.Protobuf.guid();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.TimeStamp != 0L) {
        TimeStamp = other.TimeStamp;
      }
      if (other.correlationId_ != null) {
        if (correlationId_ == null) {
          correlationId_ = new global::System.Protobuf.guid();
        }
        CorrelationId.MergeFrom(other.CorrelationId);
      }
      events_.Add(other.events_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (source_ == null) {
              source_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.VersionedEventSource();
            }
            input.ReadMessage(source_);
            break;
          }
          case 16: {
            Sequence = input.ReadUInt64();
            break;
          }
          case 26: {
            if (id_ == null) {
              id_ = new global::System.Protobuf.guid();
            }
            input.ReadMessage(id_);
            break;
          }
          case 32: {
            TimeStamp = input.ReadInt64();
            break;
          }
          case 42: {
            if (correlationId_ == null) {
              correlationId_ = new global::System.Protobuf.guid();
            }
            input.ReadMessage(correlationId_);
            break;
          }
          case 50: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
