// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dolittle/interaction/events.relativity/event_envelope.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Protobuf {

  /// <summary>Holder for reflection information generated from dolittle/interaction/events.relativity/event_envelope.proto</summary>
  public static partial class EventEnvelopeReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/interaction/events.relativity/event_envelope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventEnvelopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cjtkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMucmVsYXRpdml0eS9ldmVu",
            "dF9lbnZlbG9wZS5wcm90bxIaZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHka",
            "O2RvbGl0dGxlL2ludGVyYWN0aW9uL2V2ZW50cy5yZWxhdGl2aXR5L2V2ZW50",
            "X21ldGFkYXRhLnByb3RvGjlkb2xpdHRsZS9pbnRlcmFjdGlvbi9ldmVudHMu",
            "cmVsYXRpdml0eS9wcm9wZXJ0eV9iYWcucHJvdG8ihAEKDUV2ZW50RW52ZWxv",
            "cGUSOwoIbWV0YWRhdGEYASABKAsyKS5kb2xpdHRsZS5ldmVudHMucmVsYXRp",
            "dml0eS5FdmVudE1ldGFkYXRhEjYKBWV2ZW50GAIgASgLMicuZG9saXR0bGUu",
            "ZXZlbnRzLnJlbGF0aXZpdHkuUHJvcGVydHlCYWdCLqoCK0RvbGl0dGxlLlJ1",
            "bnRpbWUuRXZlbnRzLlJlbGF0aXZpdHkuUHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Events.Relativity.Protobuf.EventMetadataReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Protobuf.PropertyBagReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope), global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelope.Parser, new[]{ "Metadata", "Event" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents an event
  /// </summary>
  public sealed partial class EventEnvelope : pb::IMessage<EventEnvelope> {
    private static readonly pb::MessageParser<EventEnvelope> _parser = new pb::MessageParser<EventEnvelope>(() => new EventEnvelope());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Events.Relativity.Protobuf.EventEnvelopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventEnvelope(EventEnvelope other) : this() {
      Metadata = other.metadata_ != null ? other.Metadata.Clone() : null;
      Event = other.event_ != null ? other.Event.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventEnvelope Clone() {
      return new EventEnvelope(this);
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 1;
    private global::Dolittle.Runtime.Events.Relativity.Protobuf.EventMetadata metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Protobuf.EventMetadata Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 2;
    private global::Dolittle.Runtime.Events.Relativity.Protobuf.PropertyBag event_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Protobuf.PropertyBag Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Metadata, other.Metadata)) return false;
      if (!object.Equals(Event, other.Event)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (event_ != null) hash ^= Event.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (metadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Metadata);
      }
      if (event_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Event);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (event_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Event);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          metadata_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.EventMetadata();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      if (other.event_ != null) {
        if (event_ == null) {
          event_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.PropertyBag();
        }
        Event.MergeFrom(other.Event);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (metadata_ == null) {
              metadata_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.EventMetadata();
            }
            input.ReadMessage(metadata_);
            break;
          }
          case 18: {
            if (event_ == null) {
              event_ = new global::Dolittle.Runtime.Events.Relativity.Protobuf.PropertyBag();
            }
            input.ReadMessage(event_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
