/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var system_object_pb = require('../system/object_pb.js');
goog.object.extend(proto, system_object_pb);
goog.exportSymbol('proto.dolittle.events.relativity.ArrayValue', null, global);
goog.exportSymbol('proto.dolittle.events.relativity.DictionaryValue', null, global);
goog.exportSymbol('proto.dolittle.events.relativity.Value', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.events.relativity.Value = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.dolittle.events.relativity.Value.oneofGroups_);
};
goog.inherits(proto.dolittle.events.relativity.Value, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.events.relativity.Value.displayName = 'proto.dolittle.events.relativity.Value';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.events.relativity.ArrayValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dolittle.events.relativity.ArrayValue.repeatedFields_, null);
};
goog.inherits(proto.dolittle.events.relativity.ArrayValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.events.relativity.ArrayValue.displayName = 'proto.dolittle.events.relativity.ArrayValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dolittle.events.relativity.DictionaryValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dolittle.events.relativity.DictionaryValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dolittle.events.relativity.DictionaryValue.displayName = 'proto.dolittle.events.relativity.DictionaryValue';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.dolittle.events.relativity.Value.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.dolittle.events.relativity.Value.KindCase = {
  KIND_NOT_SET: 0,
  OBJECT_VALUE: 1,
  LIST_VALUE: 2,
  DICTIONARY_VALUE: 3
};

/**
 * @return {proto.dolittle.events.relativity.Value.KindCase}
 */
proto.dolittle.events.relativity.Value.prototype.getKindCase = function() {
  return /** @type {proto.dolittle.events.relativity.Value.KindCase} */(jspb.Message.computeOneofCase(this, proto.dolittle.events.relativity.Value.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.events.relativity.Value.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.events.relativity.Value.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.events.relativity.Value} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.Value.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectValue: (f = msg.getObjectValue()) && system_object_pb.Object.toObject(includeInstance, f),
    listValue: (f = msg.getListValue()) && proto.dolittle.events.relativity.ArrayValue.toObject(includeInstance, f),
    dictionaryValue: (f = msg.getDictionaryValue()) && proto.dolittle.events.relativity.DictionaryValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.events.relativity.Value}
 */
proto.dolittle.events.relativity.Value.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.events.relativity.Value;
  return proto.dolittle.events.relativity.Value.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.events.relativity.Value} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.events.relativity.Value}
 */
proto.dolittle.events.relativity.Value.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new system_object_pb.Object;
      reader.readMessage(value,system_object_pb.Object.deserializeBinaryFromReader);
      msg.setObjectValue(value);
      break;
    case 2:
      var value = new proto.dolittle.events.relativity.ArrayValue;
      reader.readMessage(value,proto.dolittle.events.relativity.ArrayValue.deserializeBinaryFromReader);
      msg.setListValue(value);
      break;
    case 3:
      var value = new proto.dolittle.events.relativity.DictionaryValue;
      reader.readMessage(value,proto.dolittle.events.relativity.DictionaryValue.deserializeBinaryFromReader);
      msg.setDictionaryValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.events.relativity.Value.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.events.relativity.Value.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.events.relativity.Value} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.Value.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectValue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      system_object_pb.Object.serializeBinaryToWriter
    );
  }
  f = message.getListValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.dolittle.events.relativity.ArrayValue.serializeBinaryToWriter
    );
  }
  f = message.getDictionaryValue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.dolittle.events.relativity.DictionaryValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional Object object_value = 1;
 * @return {?proto.dolittle.events.relativity.Object}
 */
proto.dolittle.events.relativity.Value.prototype.getObjectValue = function() {
  return /** @type{?proto.dolittle.events.relativity.Object} */ (
    jspb.Message.getWrapperField(this, system_object_pb.Object, 1));
};


/** @param {?proto.dolittle.events.relativity.Object|undefined} value */
proto.dolittle.events.relativity.Value.prototype.setObjectValue = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.dolittle.events.relativity.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.dolittle.events.relativity.Value.prototype.clearObjectValue = function() {
  this.setObjectValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolittle.events.relativity.Value.prototype.hasObjectValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ArrayValue list_value = 2;
 * @return {?proto.dolittle.events.relativity.ArrayValue}
 */
proto.dolittle.events.relativity.Value.prototype.getListValue = function() {
  return /** @type{?proto.dolittle.events.relativity.ArrayValue} */ (
    jspb.Message.getWrapperField(this, proto.dolittle.events.relativity.ArrayValue, 2));
};


/** @param {?proto.dolittle.events.relativity.ArrayValue|undefined} value */
proto.dolittle.events.relativity.Value.prototype.setListValue = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.dolittle.events.relativity.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.dolittle.events.relativity.Value.prototype.clearListValue = function() {
  this.setListValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolittle.events.relativity.Value.prototype.hasListValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DictionaryValue dictionary_value = 3;
 * @return {?proto.dolittle.events.relativity.DictionaryValue}
 */
proto.dolittle.events.relativity.Value.prototype.getDictionaryValue = function() {
  return /** @type{?proto.dolittle.events.relativity.DictionaryValue} */ (
    jspb.Message.getWrapperField(this, proto.dolittle.events.relativity.DictionaryValue, 3));
};


/** @param {?proto.dolittle.events.relativity.DictionaryValue|undefined} value */
proto.dolittle.events.relativity.Value.prototype.setDictionaryValue = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.dolittle.events.relativity.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.dolittle.events.relativity.Value.prototype.clearDictionaryValue = function() {
  this.setDictionaryValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dolittle.events.relativity.Value.prototype.hasDictionaryValue = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dolittle.events.relativity.ArrayValue.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.events.relativity.ArrayValue.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.events.relativity.ArrayValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.events.relativity.ArrayValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.ArrayValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    valuesList: jspb.Message.toObjectList(msg.getValuesList(),
    proto.dolittle.events.relativity.Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.events.relativity.ArrayValue}
 */
proto.dolittle.events.relativity.ArrayValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.events.relativity.ArrayValue;
  return proto.dolittle.events.relativity.ArrayValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.events.relativity.ArrayValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.events.relativity.ArrayValue}
 */
proto.dolittle.events.relativity.ArrayValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dolittle.events.relativity.Value;
      reader.readMessage(value,proto.dolittle.events.relativity.Value.deserializeBinaryFromReader);
      msg.addValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.events.relativity.ArrayValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.events.relativity.ArrayValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.events.relativity.ArrayValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.ArrayValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.dolittle.events.relativity.Value.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Value values = 1;
 * @return {!Array<!proto.dolittle.events.relativity.Value>}
 */
proto.dolittle.events.relativity.ArrayValue.prototype.getValuesList = function() {
  return /** @type{!Array<!proto.dolittle.events.relativity.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dolittle.events.relativity.Value, 1));
};


/** @param {!Array<!proto.dolittle.events.relativity.Value>} value */
proto.dolittle.events.relativity.ArrayValue.prototype.setValuesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.dolittle.events.relativity.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dolittle.events.relativity.Value}
 */
proto.dolittle.events.relativity.ArrayValue.prototype.addValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.dolittle.events.relativity.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.dolittle.events.relativity.ArrayValue.prototype.clearValuesList = function() {
  this.setValuesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dolittle.events.relativity.DictionaryValue.prototype.toObject = function(opt_includeInstance) {
  return proto.dolittle.events.relativity.DictionaryValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dolittle.events.relativity.DictionaryValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.DictionaryValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectMap: (f = msg.getObjectMap()) ? f.toObject(includeInstance, proto.dolittle.events.relativity.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dolittle.events.relativity.DictionaryValue}
 */
proto.dolittle.events.relativity.DictionaryValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dolittle.events.relativity.DictionaryValue;
  return proto.dolittle.events.relativity.DictionaryValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dolittle.events.relativity.DictionaryValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dolittle.events.relativity.DictionaryValue}
 */
proto.dolittle.events.relativity.DictionaryValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getObjectMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.dolittle.events.relativity.Value.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dolittle.events.relativity.DictionaryValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dolittle.events.relativity.DictionaryValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dolittle.events.relativity.DictionaryValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dolittle.events.relativity.DictionaryValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObjectMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.dolittle.events.relativity.Value.serializeBinaryToWriter);
  }
};


/**
 * map<string, Value> object = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.dolittle.events.relativity.Value>}
 */
proto.dolittle.events.relativity.DictionaryValue.prototype.getObjectMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.dolittle.events.relativity.Value>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.dolittle.events.relativity.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.dolittle.events.relativity.DictionaryValue.prototype.clearObjectMap = function() {
  this.getObjectMap().clear();
};


goog.object.extend(exports, proto.dolittle.events.relativity);
