// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dolittle/application/client/connection_status.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Application.Grpc.Client {

  /// <summary>Holder for reflection information generated from dolittle/application/client/connection_status.proto</summary>
  public static partial class ConnectionStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for dolittle/application/client/connection_status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConnectionStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNkb2xpdHRsZS9hcHBsaWNhdGlvbi9jbGllbnQvY29ubmVjdGlvbl9zdGF0",
            "dXMucHJvdG8SHGRvbGl0dGxlLnJ1bnRpbWUuYXBwbGljYXRpb24aG2dvb2ds",
            "ZS9wcm90b2J1Zi9lbXB0eS5wcm90bzJTChBDb25uZWN0aW9uU3RhdHVzEj8K",
            "B0Nvbm5lY3QSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkiACgBMAFCK6oCKERvbGl0dGxlLlJ1bnRpbWUuQXBwbGlj",
            "YXRpb24uR3JwYy5DbGllbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
