name: dolittle-runtime
services:
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 30s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    hostname: mongo
    ports:
      - 27017:27017
      
  runtime:
    image: dolittle/runtime:9.4.0
    volumes:
      - ./runtime.yml:/app/.dolittle/runtime.yml
      - ./appsettings.json:/app/appsettings.json
    ports:
      - 50052:50052
      - 50053:50053
